In [1]:
%pip install numpy

In [2]:
import numpy as np 

In [58]:
data = np.random.rand(2, 3, 4)
zerosArr = np.zeros((2,2,2))
fullArr = np.full((3,3,3), 7)
onesArr = np.ones((1,3,1))

In [22]:
customArr = np.array([[1,2,3], [1,3,4]])

In [ ]:
shapes = data.shape
sizes = data.size
types = data.dtype

In [37]:
arr = data[0]
slicer = data[0][0][0:2]
reverse = data[-1]
reverse

array([[0.98357002, 0.95717489, 0.45250011, 0.78027868, 0.64725336],
       [0.93512518, 0.56264443, 0.67706024, 0.71220257, 0.18801653],
       [0.48684638, 0.66663019, 0.48368027, 0.22341805, 0.15025418]])

In [45]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

dot = np.dot(list1, list2)
list1

array([0.54425785, 0.68633988, 0.12258367, 0.15030398, 0.60903438,
       0.85853563, 0.84936355, 0.84432531, 0.78824473, 0.40580298])

In [44]:
sorted = np.sort(list1)
sorted

array([0.0241246 , 0.22147239, 0.4819405 , 0.65797381, 0.68150002,
       0.70359779, 0.8054375 , 0.87039949, 0.92659941, 0.95529329])

In [61]:
data = data.reshape(2,3,-1)
data

array([[[0.05187426, 0.83167993, 0.63174539, 0.681664  ],
        [0.52299455, 0.13998688, 0.48775163, 0.97109632],
        [0.58196397, 0.00632453, 0.55279823, 0.59960638]],

       [[0.4255748 , 0.1519866 , 0.88587991, 0.39995411],
        [0.42151114, 0.92437287, 0.19434708, 0.69849964],
        [0.12012308, 0.73793695, 0.88770481, 0.19313936]]])